Page about granting access to projects and namespaces
appuio/appuio-cloud-docs pull request #105
Opened 2022-04-05 06:52 UTC by akosma

Resolves #47 .

## Checklist

- [x] Try to isolate changes into separate PRs (to build a better changelog).
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `how-to`, `tutorial`, `reference`, `explanation`, `cicd`, `dependency`
      as they show up in the changelog
- [x] Link this PR to related issues if applicable.

2022-04-05 07:34 UTC, tobru requested changes
Some clarification needed, maybe some input from Tarazed / @corvus-ch is needed. I would add some examples of RoleBindings (Yaml) to make things more clear. And if possible, add some hints how to get the correct name of the groups (organization and team group), not entirely sure how to find that...

2022-04-05 07:34 UTC, tobru commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +Organizations and teams are reflected as OpenShift 4.9 groups.
```suggestion
Organizations and teams are reflected as OpenShift groups.
```

2022-04-05 07:34 UTC, tobru commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +A `RoleBinding` object grants the creator of a Project or Namespace admin privileges.
That one isn't clear. Which `RoleBinding`?

2022-04-05 07:34 UTC, tobru commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +This is a default behavior in OpenShift.
That's not true IMHO? Or what does "This" refer to?

2022-04-05 07:34 UTC, tobru commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +This means that by default, all members of the owning organization are granted admin privileges by referencing the corresponding OpenShift Group.
IMHO this is APPUiO Cloud specific?

2022-04-05 07:34 UTC, tobru commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +Both RoleBindings can be deleted and replaced by something else.
Which "both"? How are they called?

2022-04-05 07:52 UTC, corvus-ch requested changes
While it is no guarantee, using https://docs.openshift.com/container-platform/latest instead of the version specific URLs is less likely to break.

I also added suggestion with RoleBindings in question.

2022-04-05 07:52 UTC, corvus-ch commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +IMPORTANT: The contents of this page rely on knowledge provided by the https://docs.openshift.com/container-platform/4.9/authentication/using-rbac.html[official OpenShift 4.9 documentation about Role
```suggestion
IMPORTANT: The contents of this page rely on knowledge provided by the https://docs.openshift.com/container-platform/latest/authentication/using-rbac.html[official OpenShift documentation about Role-Base Access Control (RBAC)], highlighting the differences in {product}.
```

2022-04-05 07:52 UTC, corvus-ch commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +A `RoleBinding` object grants the creator of a Project or Namespace admin privileges.
```suggestion
The RoleBinding object named `admin` grants the creator of a Project or Namespace admin privileges.
```

2022-04-05 07:52 UTC, corvus-ch commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +This means that by default, all members of the owning organization are granted admin privileges by referencing the corresponding OpenShift Group.
```suggestion
In addition, the RoleBinding named `namespace-owner` grants the group named equal to the Organization owning the namespace admin privileges.
This means that by default, all members of the owning organization are granted admin privileges.
```

2022-04-05 07:52 UTC, corvus-ch commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +Both RoleBindings can be deleted and replaced by something else.
Should be addressed by my suggestions.

2022-04-05 07:52 UTC, corvus-ch commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +Both RoleBindings can be deleted and replaced by something else.
```suggestion
Both RoleBindings can be changed or deleted and replaced by something else.
```

2022-04-05 07:52 UTC, corvus-ch commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +Access can be granted to any OpenShift Group (This includes that namespace owned by organization A can be managed by members of organization B or only a team of organization B)
```suggestion
Access can be granted to any OpenShift Group.
This includes that namespace owned by organization A can be managed by members of organization B or only a team of organization B.
```

2022-04-05 08:04 UTC, simu requested changes

2022-04-05 08:04 UTC, simu commented on docs/modules/ROOT/pages/how-to/grant-access.adoc
> +This means that by default, all members of the owning organization are granted admin privileges.
These paragraphs are not correct.

1. We patch the `admin` RoleBinding to grant the organization admin privileges on the project, cf. https://hub.syn.tools/appuio-cloud/references/policies/10_generate_default_rolebinding_in_ns.html
2. We create the `namespace-owner` RoleBinding, which allows the organization to view, edit and delete the Namespace object itself. Edit restrictions apply, cf. https://hub.syn.tools/appuio-cloud/references/policies/02_validate_namespace_metadata.html

Maybe rewrite the paragraphs along the lines of the suggestion below (I'm not happy  with the wording, feel free to improve it).

```suggestion
On {product}, the RoleBinding object named `admin` grants the group named equal to the Organization owning the Project or Namespace admin privileges.
This differs from the default behavior in OpenShift, where the default `admin` RoleBinding only grants the creator of a Project admin privileges.

In addition, the RoleBinding named `namespace-owner` gives the group named equal to the Organization of the Namespace object permissions to view, edit and delete the object.
```

2022-04-05 09:22 UTC, simu approved these changes

2022-04-05 11:17 UTC, tobru commented
@corvus-ch Do we need to add some example RoleBindings which make use of the organization or team groups? And do you know how one could look-up the exact name of the organization or team group? I think we should describe that...

2022-04-05 13:26 UTC, corvus-ch commented
> @corvus-ch Do we need to add some example RoleBindings which make use of the organization or team groups?

I was thinking the same, but then I failed to come up with a good example. Preferably, the example would reflect a real world use case.

> And do you know how one could look-up the exact name of the organization or team group? I think we should describe that...

No, there is no "look-up". We might add that to https://github.com/appuio/cloud-portal (copy role name on both Organizations and Teams).

2022-04-06 07:38 UTC, tobru commented
> I was thinking the same, but then I failed to come up with a good example. Preferably, the example would reflect a real world use case.

What about: Create two Teams, one "view only", one "admin" and create matching RoleBindings, then remove access on the organization level?

> No, there is no "look-up". We might add that to https://github.com/appuio/cloud-portal (copy role name on both Organizations and Teams).

Isn't the name of the organization group the same as the organization name? So we could refer to that. And for the team it's the organization name plus the team name, so we could say: Hey, look in the Portal for the exact names. Another idea could be to look into the generated RoleBindings for the organization group name. Maybe `oc get groups` only returns the group you have access to? Not sure though... Or potentially there is another command to get group membership? I'm also not sure about that.

2022-04-06 08:05 UTC, corvus-ch commented
> What about: Create two Teams, one "view only", one "admin" and create matching RoleBindings, then remove access on the organization level?

Yes, that was also my morning shower thought. We might go even further and give an example for the three levels that were available on APPUiO Public.

2022-04-06 08:10 UTC, corvus-ch commented
> Isn't the name of the organization group the same as the organization name? So we could refer to that.

Correct

> And for the team it's the organization name plus the team name

Correct.

But there is no "look-up" yet, at least to my knowledge.

> Maybe `oc get groups` only returns the group you have access to? Not sure though... Or potentially there is another command to get group membership? I'm also not sure about that.

That would be nice, but as far as I am aware, only cluster-viewer can list groups. I might be wrong, though.

> so we could say: Hey, look in the Portal for the exact names.

That was my suggestion, yes. But not only, hey go look there, but give them a "copy group name" button.

2022-04-07 06:34 UTC, tobru commented
@corvus-ch Can you bring this docs over the finishing line with @akosma so that we can merge it?

2022-04-07 06:34 UTC, tobru approved these changes

2022-04-07 11:41 UTC, corvus-ch approved these changes
I made some last clarifications. Once they are in, this is good to go. We can add examples at any time in the future. For now, it is more important to have this published.

2022-04-07 12:58 UTC, merged