Tutorial how to use GitLab Agent
appuio/appuio-cloud-docs pull request #121
Opened 2022-06-01 10:58 UTC by akosma

Fixes #113 .

## Checklist

- [x] Try to isolate changes into separate PRs (to build a better changelog).
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `how-to`, `tutorial`, `reference`, `explanation`, `cicd`, `dependency`
      as they show up in the changelog
- [x] Link this PR to related issues if applicable.

2022-06-01 12:31 UTC, ccremer requested changes

2022-06-01 12:31 UTC, ccremer commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +[source, yaml]
I usually put the filename as the title of the code snippet, but no hard feeling.
```suggestion

.gitlab-ci.yml
[source, yaml]
```

2022-06-01 12:31 UTC, ccremer commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +[source, shell]
```suggestion
[source, bash]
```

2022-06-01 12:31 UTC, ccremer commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +[source, shell]
```suggestion
[source, bash]
```

2022-06-01 12:57 UTC, akosma commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +----
Yes it does!

2022-06-01 13:01 UTC, ccremer requested changes
content LGTM, but not tested.
Please cleanup & squash all these `Update docs/modules/ROOT/pages/how-to/connect-gitlab.adoc)` commits into a single one.

2022-06-22 08:18 UTC, ccremer approved these changes
I've allowed myself to squash your commits and rebase.
If you're happy with it, feel free to merge.

2022-06-22 08:52 UTC, tobru approved these changes

2022-06-22 10:54 UTC, merged