How-To: Configure Monitoring Alerts using Alertmanager
appuio/appuio-cloud-docs pull request #141
Opened 2022-11-08 09:42 UTC by bastjan

## Checklist

- [x] Try to isolate changes into separate PRs (to build a better changelog).
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `how-to`, `tutorial`, `reference`, `explanation`, `cicd`, `dependency`
      as they show up in the changelog

2022-11-08 14:19 UTC, bastjan commented on docs/modules/ROOT/pages/how-to/configure-alertmanager.adoc
> +Wrong login credentials or missing certificates can cause the Alertmanager to fail to send alerts.
Will add a debug your webhook section in a separate PR.

2022-11-08 14:44 UTC, simu approved these changes
LGTM overall, some wording suggestions inline

2022-11-08 14:44 UTC, simu commented on docs/modules/ROOT/pages/how-to/configure-alertmanager.adoc
> +{product} allows you to configure alerts receivers to notify you when an alert is triggered.
```suggestion
{product} allows you to configure custom alert receivers to notify you when an alert is triggered.
```

2022-11-08 14:44 UTC, simu commented on docs/modules/ROOT/pages/how-to/configure-alertmanager.adoc
> +A `AlertmanagerConfig` resource defines a routing tree with a root route and child routes.
```suggestion
An `AlertmanagerConfig` resource defines a routing tree with a root route and child routes.
```

2022-11-08 14:44 UTC, simu commented on docs/modules/ROOT/pages/how-to/configure-alertmanager.adoc
> +Wrong login credentials or missing certificates can cause the Alertmanager to fail to send alerts.
```suggestion
Alertmanager may fail to send alerts when the routing configuration has wrong login credentials or missing certificates.
```

2022-11-08 14:44 UTC, simu commented on docs/modules/ROOT/pages/how-to/configure-alertmanager.adoc
> +OpenShift currently doesn't expose any logs or status information for the Alertmanager.
```suggestion
OpenShift currently doesn't expose any logs or status information for Alertmanager.
```

2022-11-08 15:52 UTC, corvus-ch requested changes
This feels like too many things cramped into one thing. This probably will confuse readers. I suggest splitting this up into different documents: one for each receiver.

While it is nice to talk about the routing capabilities, I would reduce this. Maybe go as far as to reduce this to a tip with a link to upstream documentation.

2022-11-09 08:43 UTC, corvus-ch requested changes

2022-11-09 08:43 UTC, corvus-ch commented on docs/modules/ROOT/pages/how-to/configure-alertmanager.adoc
> +        name: email
```suggestion
        name: email-alert-auth
```

2022-11-09 09:23 UTC, bastjan commented
@corvus-ch I shrunk down the initial sample and re-checked and improved manifest naming.

The initial sample is now more a ToC and helps guide the user to the correct section.

2022-11-09 14:01 UTC, bastjan commented on docs/modules/ROOT/pages/how-to/configure-alertmanager.adoc
> +Wrong login credentials or missing certificates can cause the Alertmanager to fail to send alerts.
Added in https://github.com/appuio/appuio-cloud-docs/pull/141/commits/7618e3135fe88b508320d44955d82f88daf5f19b

2022-11-09 14:12 UTC, corvus-ch approved these changes

2022-11-09 14:25 UTC, merged