Updated getting started instructions
appuio/appuio-cloud-docs pull request #169
Opened 2023-04-25 12:39 UTC by akosma

This PR updates the instructions in the "Getting Started" guide following the new self-signup feature.

## Checklist

- [x] Try to isolate changes into separate PRs (to build a better changelog).
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `how-to`, `tutorial`, `reference`, `explanation`, `cicd`, `dependency`
      as they show up in the changelog
- [ ] Link this PR to related issues if applicable.

2023-04-25 13:35 UTC, corvus-ch requested changes
Missed a change on login. Also, I suggest adding some links for convenience.

2023-04-25 13:35 UTC, corvus-ch commented on docs/modules/ROOT/pages/tutorials/getting-started.adoc
> +Login to the https://portal.appuio.cloud/[APPUiO Cloud Portal] using your newly created account. You will be asked to provide a password and setup Two-Factor Authentication (2FA) in your account.
```suggestion
Login to the https://portal.appuio.cloud/[APPUiO Cloud Portal] using your newly created account.
```

No, no password. I am uncertain if 2FA is enforced.

2023-04-25 13:35 UTC, corvus-ch commented on docs/modules/ROOT/pages/tutorials/getting-started.adoc
> +The first thing you need to do in the https://portal.appuio.cloud/[APPUiO Cloud Portal] is to add your billing information, and then to create an organization for yourself and your team.
```suggestion
The first thing you need to do in the https://portal.appuio.cloud/[APPUiO Cloud Portal] is to add your https://portal.appuio.cloud/billingentities/$new?edit=y[billing information, and then to https://portal.appuio.cloud/organizations/$new[create an organization] for yourself and your team.
```

2023-04-25 13:35 UTC, corvus-ch commented on docs/modules/ROOT/pages/tutorials/getting-started.adoc
>  WARNING: If you don't choose a default organization, you won't be able to create new projects in the OpenShift web console later.
```suggestion
WARNING: If you don't https://portal.appuio.cloud/user[choose a default organization], you won't be able to create new projects in the OpenShift web console later.
```

2023-04-25 13:47 UTC, akosma commented
Changes added, thanks!

2023-04-26 07:29 UTC, corvus-ch approved these changes
Apart from the missing `]` this is no looking good.

2023-04-26 07:29 UTC, corvus-ch commented on docs/modules/ROOT/pages/tutorials/getting-started.adoc
> +The first thing you need to do in the https://portal.appuio.cloud/[APPUiO Cloud Portal] is to add your https://portal.appuio.cloud/billingentities/$new?edit=y[billing information, and then to https:/
```suggestion
The first thing you need to do in the https://portal.appuio.cloud/[APPUiO Cloud Portal] is to add your https://portal.appuio.cloud/billingentities/$new?edit=y[billing information], and then to https://portal.appuio.cloud/organizations/$new[create an organization] for yourself and your team.
```

2023-04-26 07:57 UTC, akosma commented
All good? Can we merge?

2023-04-26 07:58 UTC, merged