New page with GitLab-specific instructions
appuio/appuio-cloud-docs pull request #60
Opened 2021-12-15 08:11 UTC by akosma

This PR provides a new page with instructions about how to connect GitLab to APPUiO Cloud for GitOps scenarios.

## Checklist

- [x] Try to isolate changes into separate PRs (to build a better changelog).
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `how-to`, `tutorial`, `reference`, `explanation`, `cicd`, `dependency`
      as they show up in the changelog
- [ ] Link this PR to related issues if applicable.

2021-12-15 09:06 UTC, tobru approved these changes
LGTM - Let's have another review (I pinged some VSHNeers)

2021-12-15 09:06 UTC, tobru commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +** Kubernetes cluster name: "APPUiO Cloud."
I would add the zone name here as well.

2021-12-15 10:01 UTC, akosma commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +** Kubernetes cluster name: "APPUiO Cloud."
I just added it.

2021-12-15 10:18 UTC, ccremer requested changes

2021-12-15 11:29 UTC, ccremer commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +. Click the btn[Add Kubernetes cluster]
```suggestion
. Click the button btn:[Add Kubernetes cluster]
```

2021-12-15 11:29 UTC, ccremer commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +<1> Name of the secret created in the previous step.
Maybe only use the minimal path to spec?
Besides, we should probably not encourage the use of `DeploymentConfig` anymore?
```suggestion
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-name
spec:
  template:
    spec:
      imagePullSecrets:
        - name: gitlab-pull-secret # <1>
      ...
----
<1> Name of the secret created in the previous step.
```

2021-12-15 13:41 UTC, corvus-ch approved these changes
Nothing left for me. @ccremer did cover it all. As soon as his points are resolved, this is fine for mee too.

2021-12-16 11:29 UTC, akosma commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +This page explains how to connect your GitLab project to APPUiO Cloud for your GitOps operations.
This breaks the current version of the search engine, sadly. The title of the search engine result says literally "Connect GitLab to {product}" in that case. I don't agree this is a good idea, to be honest. Why is this a variable? How often are we going to change this value? I don't get it.

2021-12-16 11:31 UTC, akosma commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +This page explains how to connect your GitLab project to APPUiO Cloud for your GitOps operations.
"makes typing a bit easier" => I doubt it. 😆

2021-12-16 11:36 UTC, akosma commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +This page explains how to connect your GitLab project to APPUiO Cloud for your GitOps operations.
I think both sections in this document are GitOps specific, so the description applies correctly.

2021-12-16 11:43 UTC, akosma commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +This page explains how to connect your GitLab project to APPUiO Cloud for your GitOps operations.
Search engine results:

![Selection_001](https://user-images.githubusercontent.com/55348/146365584-f942582c-03fb-4a7d-ab0d-d59e795a0dc7.png)

2021-12-16 11:54 UTC, akosma commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +This page explains how to connect your GitLab project to APPUiO Cloud for your GitOps operations.
I just opened #61 to address this point in detail. I'm closing this conversation for now.

2022-01-06 14:43 UTC, akosma commented on docs/modules/ROOT/pages/how-to/connect-gitlab.adoc
> +This page explains how to connect your GitLab project to APPUiO Cloud for your GitOps operations.
`vshn/antora-indexer-cli:1.12` solves this issue.

2022-01-06 14:52 UTC, akosma commented
Ready to merge, @ccremer could you please check again? Thanks.

2022-01-06 15:59 UTC, ccremer approved these changes

2022-01-07 08:58 UTC, merged